variables:
    GIT_STRATEGY: clone

stages:
  - deploy xalt

backup_slurmquota:
  stage: deploy xalt
  tags:
    - shell.login.pi.sjtu.edu.cn
  script:
    - rsync -avr --delete --progress xalt /lustre/share/singularity/modules/xalt
