variables:
    GIT_STRATEGY: clone

stages:
  - deploy xalt

deploy_xalt_module_to_lustre:
  stage: deploy xalt
  tags:
    - shell.login.pi.sjtu.edu.cn
  script:
    - sudo rsync -avr --delete --progress xalt/ /lustre/share/singularity/modules/xalt/
